# Docs for Azure Web Apps Deploy: https://github.com/Azure/webapps-deploy
# Docs for Azure Login: https://github.com/Azure/login

name: Build and deploy full-stack Node.js app (frontend + backend) to Azure Web App - Pika

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 🧱 Stap 1 — Build frontend
      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build

      # 📦 Stap 2 — Installeer backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # 🔗 Stap 3 — Verplaats frontend build naar backend-map
      - name: Move frontend build into backend folder
        run: |
          rm -rf backend/build
          mkdir -p backend/build
          cp -r frontend/build/* backend/build/

      # 📤 Stap 4 — Upload backend als artifact voor deployment
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: fullstack-app
          path: backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: fullstack-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AB0E27E8FED54513A988F09EBCB21954 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D427735105674B0CBBBFDA7D5246B9EF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3A49B30E4B8F416DA919318B47DC4EB8 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Pika'
          slot-name: 'Production'
          package: .
