name: Build and deploy full-stack Node.js app to Azure Web App - Pika

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 4️⃣ Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # 6️⃣ Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AB0E27E8FED54513A988F09EBCB21954 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D427735105674B0CBBBFDA7D5246B9EF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8CCF6D7C05294AC6AE20EAD30F7B05B8 }}

      # 7️⃣ Deploy backend to Azure
      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Pika'
          slot-name: 'Production'
          package: './backend'