name: Build and deploy full-stack Node.js app to Azure Web App - Pika

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3️⃣ Install & Build frontend (React)
      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          CI=false npm run build

      # 4️⃣ Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # 5️⃣ Copy frontend build to backend (optional for serving frontend via backend)
      - name: Copy frontend build into backend
        run: |
          rm -rf backend/build
          mkdir -p backend/build
          cp -r frontend/build/* backend/build/

      # 6️⃣ Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AB0E27E8FED54513A988F09EBCB21954 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D427735105674B0CBBBFDA7D5246B9EF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3A49B30E4B8F416DA919318B47DC4EB8 }}

      # 7️⃣ Deploy backend to Azure
      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Pika'
          slot-name: 'Production'
          package: './backend'